// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hmniPTDOTk7az7hagtEwMAGCzWPklpI',
    appId: '1:23739853102:web:e38bca82cc0d9b41ee72bf',
    messagingSenderId: '23739853102',
    projectId: 'hello-app-e8f88',
    authDomain: 'hello-app-e8f88.firebaseapp.com',
    storageBucket: 'hello-app-e8f88.firebasestorage.app',
    measurementId: 'G-DB2ZGBPLXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmspxTv4eklFZbrzANQskn8heUIFGJs7A',
    appId: '1:23739853102:android:60ae43cce571b3e1ee72bf',
    messagingSenderId: '23739853102',
    projectId: 'hello-app-e8f88',
    storageBucket: 'hello-app-e8f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9JgCT4mq2VRPpu6TEYKGa7Jkkc9EA-p4',
    appId: '1:23739853102:ios:ff837bfd353d204bee72bf',
    messagingSenderId: '23739853102',
    projectId: 'hello-app-e8f88',
    storageBucket: 'hello-app-e8f88.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9JgCT4mq2VRPpu6TEYKGa7Jkkc9EA-p4',
    appId: '1:23739853102:ios:ff837bfd353d204bee72bf',
    messagingSenderId: '23739853102',
    projectId: 'hello-app-e8f88',
    storageBucket: 'hello-app-e8f88.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_hmniPTDOTk7az7hagtEwMAGCzWPklpI',
    appId: '1:23739853102:web:7a750056bd234c88ee72bf',
    messagingSenderId: '23739853102',
    projectId: 'hello-app-e8f88',
    authDomain: 'hello-app-e8f88.firebaseapp.com',
    storageBucket: 'hello-app-e8f88.firebasestorage.app',
    measurementId: 'G-NCPXMMCV5W',
  );
}
